version: '3.4'

services:
  node1:
    image: pydock
    build:
      context: ./del-app
      dockerfile: ./Dockerfile
    volumes:
        - './del-app/data_repo/node1/client.data:/app/data/client.data'
        - './del-app/data_repo/node1/fashion-mnist_train.csv:/app/data/fashion-mnist.csv'
    networks:
      delnet:
        ipv4_address: 172.16.238.11
  node2:
    image: pydock
    build:
      context: ./del-app
      dockerfile: ./Dockerfile
    volumes:
        - './del-app/data_repo/node2/client.data:/app/data/client.data'
        - './del-app/data_repo/node2/fashion-mnist_train.csv:/app/data/fashion-mnist.csv'
    networks:
      delnet:
        ipv4_address: 172.16.238.12
  node3:
    image: pydock
    build:
      context: ./del-app
      dockerfile: ./Dockerfile
    volumes:
        - './del-app/data_repo/node3/client.data:/app/data/client.data'
        - './del-app/data_repo/node3/fashion-mnist_train.csv:/app/data/fashion-mnist.csv'
    networks:
      delnet:
        ipv4_address: 172.16.238.13


networks:
  delnet:
    ipam:
      config:
        - subnet: 172.16.238.0/24
    
